### ISSUE TITLE
Mathematical signs are misaligned

### ISSUE THREAD

**Issue by thlinard** [TypeNetwork/Raleway#20]
The horizontal bar of + − ÷ should be the same, and aligned vertically (in the middle) with × =. And = should be two − (minus sign).

Ideally, there should be two sets: one for `onum`, the other for `lnum`, for proper vertical alignment with the figures. But the problem described here is the most urgent.

<img width="795" alt="Raleway" src="https://user-images.githubusercontent.com/13808824/91022653-cef2fa80-e5f5-11ea-94de-a0b236ddf78e.png">

**Comment by thlinard** [comment]
More complete specimen (1×<>+÷−¬=≠±≤≥3), with Raleway Thin, default figures, and Raleway Black + `lnum` feature:

<img width="1533" alt="Raleway" src="https://user-images.githubusercontent.com/13808824/91167232-e56f8380-e6d3-11ea-8660-b37a7991ee35.png">

The signs are a bit low to get along with lining figures.

**Comment by pichotta** [comment]
The mathematical alignment is a foundry related design decision and fix. See the above mentioned related issue.
"Mathematical signs are misaligned theleagueof/raleway#20"

**Comment by thlinard** [comment]
> The mathematical alignment is a foundry related design decision and fix. See the above mentioned related issue.
> "Mathematical signs are misaligned [theleagueof/raleway#20](https://github.com/theleagueof/raleway/issues/20)"

I find calling this a "design decision" a little too lenient (otherwise we can also call "design decisions" bad kerning and design errors as reported in https://www.twardoch.com/download/polishhowto/), but I understand that is not your responsibility. It's sometimes difficult to know which is the primary repository of a project!

It would be necessary to change the primary repository indicated in https://github.com/google/fonts/blob/master/ofl/raleway/DESCRIPTION.en_us.html. What do you think, @alerque?

**Comment by alerque** [comment]
I agree that's a bit lenient and I'd call it an outright bug, but the history of "this" repository is a mess. At the time TypeNetwork was commissioned to improve this font, the best available project was *not* the original upstream. They forked from Impallari's repository which was unfortunately not a fork, it was a new repository with a disconnected history from the original.

Since then the original (The League of Movable Type) project has tried to integrate all the best changes floating around the web and I believe [theleagueof/raleway](https://github.com/theleagueof/raleway) should be considered canonical. That leaves *this TypeNetwork repository floating in limbo*. It is neither the latest nor canonical upstream. The League's repository has everything from TypeNetwork's efforts integrated, and a few extra things fixed as well. This particular issue is being tracked there and fixing it should involve forking and PRing against that repository.

Long term I suggest the best thing to to with this repository would be to add a commit to HEAD‌ with a note about the new canonical location, then use GitHub's archive feature to mark it as inactive and block new issues/PRs. Then in TypeNetwork does want to contribute something further they can fork the actual canonical repository and work from there. Now that the League is active again that's a realistic option.

**Comment by alerque** [comment]
And yes @thlinard I would love to see Google Fonts acknowledge the League as the official upstream of this font again. I realize they commissioned TypeNetwork to extend it and at the time the League wasn't very active development wise so it might not have been feasible to submit contributions upstream, but whatever the situation was then it should be possible to do so now. Indeed I've done most of the work to get everything upstreamed already, only the linkage and this floating repository is still outdated.

**Comment by thlinard** [comment]
Yes, I absolutely doubt there is a design decision in the misalignment of the math signs. When a designer does that, he doesn't create art, he just ignores what he's doing.

That's okay, mind you, we learn every day in typography, and it goes hand in hand with the little attention paid to vertical axes beyond the baseline in Latin typography, which is very common, like the absence of a `case` feature for -–—({[«•»]})@¿¡, or the `onum` feature which doesn't include monetary or mathematical symbols (because the relation between lining figures and capitals being ignored, the relationship between the mathematical axis and the `case` function is also not understood).

Otherwise, let's hope that the consolidation of the League repository as the primary repository for Raleway can be done!
